### ISSUE TITLE
Crash on installation

### ISSUE THREAD

**Issue by arxenix** [fraxiinus/ReplayBook#211]
**Describe the bug**
ReplayBook 1.6.1 crashes near the end of installation, when clicking "Next" after the downloading static data step is finished.

**To Reproduce**
1. Download replaybook
2. Extract zip and run exe
4. complete steps to select appropriate directories, get to static data step and wait for static data to finish downloading
5. click next
6. installer crashes

**Expected behavior**
don't crash

**Desktop (please complete the following information):**
 - OS: Win10 21H2 19044.2006

**Additional context**
tail of logs:
```
INFO  | 2022-10-11T06:42:11    | DataDragonClient.cs -> DownloadRuneImages() -> 152 | Made successful HTTP request https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsAdaptiveForceIcon.png
INFO  | 2022-10-11T06:42:11    | DataDragonClient.cs -> DownloadRuneImages() -> 152 | Made successful HTTP request https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsHealthScalingIcon.png
INFO  | 2022-10-11T06:42:11    | DataDragonClient.cs -> DownloadRuneImages() -> 152 | Made successful HTTP request https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsCDRScalingIcon.png
INFO  | 2022-10-11T06:42:11    | DataDragonClient.cs -> DownloadRuneImages() -> 152 | Made successful HTTP request https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsAttackSpeedIcon.png
ERROR | 2022-10-11T06:42:16    | MainWindow.xaml.cs -> .ctor() -> 53 | System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Invalid data context
   at Fraxiinus.ReplayBook.UI.Main.Pages.WelcomeSetupFinish.get_Context()
   at Fraxiinus.ReplayBook.UI.Main.Pages.WelcomeSetupFinish..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at ModernWpf.Controls.Frame.Navigate(Type sourcePageType)
   at Fraxiinus.ReplayBook.UI.Main.Views.WelcomeSetupWindow.GoToNextPage()
   at Fraxiinus.ReplayBook.UI.Main.Views.WelcomeSetupWindow.NextButton_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by AlterGu** [comment]
me too

**Comment by fraxiinus** [comment]
As a workaround, you can close the setup window to get straight to ReplayBook, skipping the part that crashes.
