### ISSUE TITLE
Static data breaks after deleting cache

### ISSUE THREAD

**Issue by fraxiinus** [fraxiinus/ReplayBook#272]
Multiple bundles are still deleted in settings, refreshing list does not fix.

Log

```txt
ERROR | 2023-06-01T17:18:26    | StaticDataManager.cs -> GetAtlasImage() -> 214 | could not load image for: champion4.png - 13.10 - System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1.get_Item(Int32 index)
   at Fraxiinus.ReplayBook.StaticData.Models.ObservableBundle.GetAtlasImage(String imageSource, String dataPath)
   at Fraxiinus.ReplayBook.StaticData.StaticDataManager.GetAtlasImage(String source, String patchVersion)
```

**Comment by fraxiinus** [comment]
Deleting most recent bundle and re-downloading it fixes it

**Comment by fraxiinus** [comment]
Cannot reproduce
